name: Daily Scrape

on:
  schedule:
    - cron: '0 2 * * *'   # Runs daily at 2:00 AM UTC
  workflow_dispatch:      # Also allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # or your Go version

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run scraper
        working-directory: ./cmd
        run: |
          go run main.go

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update output.json from scraper"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
